export const archetypeList: { name: string; isOrigin: boolean }[] = [
  { name: "Seeker", isOrigin: true },
  { name: "Magic Seeker", isOrigin: false },
  { name: "Soul Hacker", isOrigin: false },
  { name: "Mage", isOrigin: true },
  { name: "Wizard", isOrigin: false },
  { name: "Elemental Master", isOrigin: false },
  { name: "Warlock", isOrigin: false },
  { name: "Warrior", isOrigin: true },
  { name: "Swordmaster", isOrigin: false },
  { name: "Samurai", isOrigin: false },
  { name: "Royal Warrior", isOrigin: false },
  { name: "Knight", isOrigin: true },
  { name: "Magic Knight", isOrigin: false },
  { name: "Paladin", isOrigin: false },
  { name: "Dark Knight", isOrigin: false },
  { name: "Royal Knight", isOrigin: false },
  { name: "Thief", isOrigin: true },
  { name: "Assassin", isOrigin: false },
  { name: "Ninja", isOrigin: false },
  { name: "Royal Thief", isOrigin: false },
  { name: "Masked Dancer", isOrigin: true },
  { name: "Persona Master", isOrigin: false },
  { name: "Royal Masked Dancer", isOrigin: false },
  { name: "Summoner", isOrigin: true },
  { name: "Devil Summoner", isOrigin: false },
  { name: "Royal Summoner", isOrigin: false },
  { name: "Berserker", isOrigin: true },
  { name: "Destroyer", isOrigin: false },
  { name: "Royal Berserker", isOrigin: false },
  { name: "Gunner", isOrigin: true },
  { name: "Sniper", isOrigin: false },
  { name: "Dragoon", isOrigin: false },
  { name: "Healer", isOrigin: true },
  { name: "Cleric", isOrigin: false },
  { name: "Saviour", isOrigin: false },
  { name: "Brawler", isOrigin: true },
  { name: "Pugilist", isOrigin: false },
  { name: "Martial Artist", isOrigin: false },
  { name: "Commander", isOrigin: true },
  { name: "General", isOrigin: false },
  { name: "Warlord", isOrigin: false },
  { name: "Faker", isOrigin: true },
  { name: "Trickster", isOrigin: false },
  { name: "Merchant", isOrigin: true },
  { name: "Tycoon", isOrigin: false },
];
